## Ejercico clase calcular spread c Roll

In [ ]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt

In [27]:
# Importamos archivos 

data = pd.read_csv("btc_project_train.csv")
data.head(20)

,Timestamp,Gmtoffset,Datetime,Open,High,Low,Close,Volume
0,1654041600,0,2022-06-01 00:00:00,31803.693359,31834.984375,31803.693359,31834.984375,NaN
1,1654041900,0,2022-06-01 00:05:00,31834.910156,31853.056640,31834.910156,31853.056640,NaN
2,1654042200,0,2022-06-01 00:10:00,31854.175781,31854.175781,31747.339843,31747.378906,NaN
3,1654042500,0,2022-06-01 00:15:00,31750.771484,31840.392578,31750.771484,31840.392578,39202816.0
4,1654042800,0,2022-06-01 00:20:00,31844.460937,31844.460937,31777.644531,31777.644531,NaN
5,1654043100,0,2022-06-01 00:25:00,31730.138671,31795.111328,31730.138671,31795.111328,49233920.0
6,1654043400,0,2022-06-01 00:30:00,31792.123046,31849.695312,31792.123046,31849.695312,88207360.0
7,1654043700,0,2022-06-01 00:35:00,31850.685546,31893.925781,31850.685546,31882.439453,20967424.0
8,1654044000,0,2022-06-01 00:40:00,31878.117187,31935.921875,31878.117187,31933.105468,76804096.0
9,1654044300,0,2022-06-01 00:45:00,31935.130859,31935.130859,31928.966796,31934.746093,NaN
10,1654044600,0,2022-06-01 00:50:00,31917.759765,31917.759765,31899.501953,31899.888671,NaN
11,1654044900,0,2022-06-01 00:55:00,31907.882812,31957.285156,31907.882812,31950.976562,8099840.0
12,1654045200,0,2022-06-01 01:00:00,31944.302734,31944.302734,31890.808593,31890.808593,NaN
13,1654045500,0,2022-06-01 01:05:00,31896.804687,31896.804687,31889.578125,31890.294921,NaN
14,1654045800,0,2022-06-01 01:10:00,31888.505859,31903.986328,31888.505859,31903.986328,14434304.0
15,1654046100,0,2022-06-01 01:15:00,31901.640625,31904.214843,31899.298828,31902.710937,2021376.0
16,1654046400,0,2022-06-01 01:20:00,31906.279296,31906.279296,31881.916015,31881.916015,NaN
17,1654046700,0,2022-06-01 01:25:00,31856.466796,31885.212890,31856.466796,31885.212890,NaN
18,1654047000,0,2022-06-01 01:30:00,31881.185546,31906.560546,31881.185546,31906.560546,3360768.0
19,1654047300,0,2022-06-01 01:35:00,31909.564453,31909.564453,31866.322265,31869.816406,NaN

In [28]:
#Eliminamos los valores nulos
data = data.dropna()
data

,Timestamp,Gmtoffset,Datetime,Open,High,Low,Close,Volume
3,1654042500,0,2022-06-01 00:15:00,31750.771484,31840.392578,31750.771484,31840.392578,39202816.0
5,1654043100,0,2022-06-01 00:25:00,31730.138671,31795.111328,31730.138671,31795.111328,49233920.0
6,1654043400,0,2022-06-01 00:30:00,31792.123046,31849.695312,31792.123046,31849.695312,88207360.0
7,1654043700,0,2022-06-01 00:35:00,31850.685546,31893.925781,31850.685546,31882.439453,20967424.0
8,1654044000,0,2022-06-01 00:40:00,31878.117187,31935.921875,31878.117187,31933.105468,76804096.0
...,...,...,...,...,...,...,...,...
166409,1703968800,0,2023-12-30 20:40:00,42249.703125,42249.703125,42230.046875,42236.199218,29988864.0
166436,1703976900,0,2023-12-30 22:55:00,42187.773437,42193.500000,42132.539062,42162.042968,21775360.0
166438,1703977500,0,2023-12-30 23:05:00,42189.187500,42229.175781,42189.187500,42229.023437,17854464.0
166439,1703977800,0,2023-12-30 23:10:00,42228.398437,42228.398437,42205.917968,42227.460937,4566016.0
166449,1703980800,0,2023-12-31 00:00:00,42152.097656,42198.000000,42152.097656,42198.000000,583680.0

In [29]:
data[["Datetime", "Close"]]

                   Datetime         Close
3       2022-06-01 00:15:00  31840.392578
5       2022-06-01 00:25:00  31795.111328
6       2022-06-01 00:30:00  31849.695312
7       2022-06-01 00:35:00  31882.439453
8       2022-06-01 00:40:00  31933.105468
...                     ...           ...
166409  2023-12-30 20:40:00  42236.199218
166436  2023-12-30 22:55:00  42162.042968
166438  2023-12-30 23:05:00  42229.023437
166439  2023-12-30 23:10:00  42227.460937
166449  2023-12-31 00:00:00  42198.000000

[87426 rows x 2 columns]

In [30]:
precio = data["Close"]
delta = precio.diff().dropna()
cov = delta.cov(delta.shift(1).dropna())

In [31]:
#Calculamos nuestro window

In [32]:

#Usamos la función rolling window para calcular el spread
window = 20
data['spread'] = data['Close'].rolling(window=window).cov(data['Close'].shift(1))
data[['Datetime', 'Close', 'spread']].head(20)

               Datetime         Close  spread
3   2022-06-01 00:15:00  31840.392578     NaN
5   2022-06-01 00:25:00  31795.111328     NaN
6   2022-06-01 00:30:00  31849.695312     NaN
7   2022-06-01 00:35:00  31882.439453     NaN
8   2022-06-01 00:40:00  31933.105468     NaN
11  2022-06-01 00:55:00  31950.976562     NaN
14  2022-06-01 01:10:00  31903.986328     NaN
15  2022-06-01 01:15:00  31902.710937     NaN
18  2022-06-01 01:30:00  31906.560546     NaN
23  2022-06-01 01:55:00  31899.189453     NaN
28  2022-06-01 02:20:00  31815.779296     NaN
29  2022-06-01 02:25:00  31774.214843     NaN
30  2022-06-01 02:30:00  31798.832031     NaN
31  2022-06-01 02:35:00  31805.595703     NaN
33  2022-06-01 02:45:00  31802.310546     NaN
35  2022-06-01 02:55:00  31810.035156     NaN
37  2022-06-01 03:05:00  31768.519531     NaN
40  2022-06-01 03:20:00  31741.445312     NaN
41  2022-06-01 03:25:00  31737.587890     NaN
43  2022-06-01 03:35:00  31674.390625     NaN